require File.join(
  File.dirname(`node --print "require.resolve('react-native/package.json')"`),
  "scripts/react_native_pods"
)

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'TikTokFeed' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Source - https://stackoverflow.com/a/79921410
  # Posted by Waseem Kurne
  # Retrieved 2026-07-23, License - CC BY-SA 4.0

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Allow non-modular includes in framework modules
        config.build_settings['CLANG_ALLOW_NON_MODULAR_IN_FRAMEWORK_MODULES'] = 'YES'
      end

      # Fix for Xcode 26.4 build error
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end
end